version: '2'

services:
    trkir_www:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                BUILD: stable
                PORT: 3061
        ports:
            - 3061:3061
        env_file:
            - ./docker/.env
